- _target_: paragem.distances.DistanceAbundanceError
  _convert_: partial
  exp_data_path: ${data.exp_data_path.0}
  exp_sol_keys: ${data.exp_sol_keys}
  exp_t_key: ${data.exp_t_key}

- _target_: paragem.distances.DistanceAbundanceError
  _convert_: partial
  exp_data_path: ${data.exp_data_path.1}
  exp_sol_keys: ${data.exp_sol_keys}
  exp_t_key: ${data.exp_t_key}
