_target_: bk_comms.community.Community
_convert_: partial
model_paths: 
  - ${cfg.wd}/models/S_cerevisiae/iMM904.xml
model_names:
  - iMM904
smetana_analysis_path: ${cfg.wd}/carveme_output/L_lactis_fbc_delGLUSx_delGLUSy_detailed.tsv
media_path: ${cfg.wd}/media/media_db_CDM35.tsv
media_name: CDM35
enable_toxin_interactions: True
objective_reaction_keys:
  - BIOMASS_SC5_notrace
initial_populations:
  - 0.0062