_convert_: partial
_target_: bk_comms.community.Community
initial_populations:
- 0.004
- 0.004
- 0.004
- 0.004
- 0.004
- 0.004

media_name: M2
media_path: ${cfg.wd}/media/melanie_data_media.tsv
model_names:
  - B_longum_subsp_longum
  - C_perfringens_S107
  - E_coli_IAI1
  - L_paracasei
  - L_plantarum
  - S_salivarius
  - C_ramosum

model_paths:
- ${cfg.wd}/models/melanie_data_models/B_longum_subsp_longum.xml
- ${cfg.wd}/models/melanie_data_models/C_perfringens_S107.xml
- ${cfg.wd}/models/melanie_data_models/E_coli_IAI1.xml
- ${cfg.wd}/models/melanie_data_models/L_paracasei.xml
- ${cfg.wd}/models/melanie_data_models/L_plantarum.xml
- ${cfg.wd}/models/melanie_data_models/S_salivarius.xml
- ${cfg.wd}/models/melanie_data_models/C_ramosum.xml

objective_reaction_keys:
- Growth
- Growth
- Growth
- Growth
- Growth
- Growth
- Growth
- Growth

smetana_analysis_path: ${cfg.wd}/smetana_analysis/melanie_data_detailed.tsv

initial_population_prior: ${cfg.sampler.init_population_sampler}
max_exchange_prior: ${cfg.sampler.max_uptake_sampler}
k_val_prior: ${cfg.sampler.k_val_sampler}
toxin_interaction_prior: ${cfg.sampler.toxin_interaction_sampler}

enable_toxin_interactions: True
