_convert_: partial
_target_: bk_comms.community.Community
initial_populations:
- 0.0001
- 0.0001

media_name: M2
media_path: ${cfg.wd}/media/melanie_data_media.tsv
model_names:
  - C_perfringens_S107
  - E_coli_IAI1

model_paths:
- ${cfg.wd}/models/melanie_data_models/C_perfringens_S107.xml
- ${cfg.wd}/models/melanie_data_models/E_coli_IAI1.xml

objective_reaction_keys:
- Growth
- Growth

smetana_analysis_path: ${cfg.wd}/smetana_analysis/melanie_data_detailed.tsv


enable_toxin_interactions: True
