_convert_: partial
_target_: bk_comms.community.Community
initial_populations:
- 0.000327941
- 0.000299055
- 0.000000000
- 0.000434989
- 0.000036702
- 0.003901312

media_name: M2
media_path: ${cfg.wd}/media/melanie_data_media.tsv
model_names:
  - B_longum_subsp_longum
  - C_perfringens_S107
  - E_coli_IAI1
  - L_paracasei
  - L_plantarum
  - S_salivarius

model_paths:
- ${cfg.wd}/models/melanie_data_models/B_longum_subsp_longum.xml
- ${cfg.wd}/models/melanie_data_models/C_perfringens_S107.xml
- ${cfg.wd}/models/melanie_data_models/E_coli_IAI1.xml
- ${cfg.wd}/models/melanie_data_models/L_paracasei.xml
- ${cfg.wd}/models/melanie_data_models/L_plantarum.xml
- ${cfg.wd}/models/melanie_data_models/S_salivarius.xml

smetana_analysis_path: ${cfg.wd}/smetana_analysis/melanie_data_detailed.tsv
use_parsimonius_fba: false
