_convert_: partial
_target_: bk_comms.community.Community
enable_toxin_interactions: false
initial_populations:
- 0.05
media_name: null
media_path: null
model_names:
- O_splanchnicus
model_paths:
- ${cfg.wd}/models/melanie_data_models/O_splanchnicus.xml
objective_reaction_keys:
- Growth
smetana_analysis_path: ${cfg.wd}/smetana_analysis/melanie_data_detailed.tsv
