_convert_: partial
_target_: bk_comms.community.Community
initial_populations:
- 0.05
media_name: null
media_path: null
model_names:
- R_intestinalis
model_paths:
- ${cfg.wd}/models/melanie_data_models/R_intestinalis.xml
smetana_analysis_path: ${cfg.wd}/smetana_analysis/melanie_data_detailed.tsv
use_parsimonius_fba: false
