_target_: bk_comms.parameter_estimation.SimpleSimulate
n_particles_batch: 10
max_simulations: 5
hotstart_particles_regex: null
simulator: ${cfg.simulator}
experiment_name: ${cfg.experiment_name}
base_community: ${cfg.community}
output_dir: ${cfg.output_dir}
particle_filter: ${cfg.filter}