_target_: bk_comms.parameter_estimation.SimpleSimulate
experiment_name: ${experiment_name}
distance_object: ${distance}
base_community: ${community}
output_dir: ${output_dir}
simulator: ${simulator}
sim_media_names: ${sim_media_names}
n_particles_batch: 10
population_size: 50
hotstart_particles_regex: 
generation_idx: 0
