_target_: bk_comms.parameter_estimation.NSGAII
population_size: 10
n_particles_batch: 5
mutation_probability: 0.05
hotstart_particles_regex:
generation_idx: 0
max_generations: 1
crossover_type: parameterwise
mutate_type: parameterwise
sim_media_names: ${sim_media_names}
simulator: ${simulator}
experiment_name: ${experiment_name}
base_community: ${community}
distance_object: ${distance}
output_dir: ${output_dir}
particle_filter: ${filter}