_target_: paragem.parameter_optimization.SampleSimulate
population_size: 10
n_particles_batch: 10
generation_idx: 0
sim_media_names: ${sim_media_names}
simulator: ${simulator}
experiment_name: ${experiment_name}
base_community: ${community}
distance_object: ${distance}
experiment_dir: ${experiment_dir}
run_idx: ${run_idx}
particle_filter: ${filter}
