_convert_: partial
_target_: bk_comms.community.Community
enable_toxin_interactions: false
initial_population_prior: ${cfg.sampler.init_population_sampler}
initial_populations:
- 0.05
k_val_prior: ${cfg.sampler.k_val_sampler}
max_exchange_prior: ${cfg.sampler.max_uptake_sampler}
media_name: null
media_path: null
model_names:
- E_rectale
model_paths:
- ${cfg.wd}/models/melanie_data_models/E_rectale.xml
objective_reaction_keys:
- Growth
smetana_analysis_path: ${cfg.wd}/smetana_analysis/melanie_data_detailed.tsv
toxin_interaction_prior: null
