_target_: bk_comms.community.Community
_convert_: partial
model_paths:
  - ${cfg.wd}/models/L_lactis/L_lactis_fbc_delGLUSx_delGLUSy.xml
  - ${cfg.wd}/models/S_cerevisiae/iMM904.xml
model_names:
  - L_lactis_fbc_delGLUSx_delGLUSy
  - iMM904
smetana_analysis_path: ${cfg.wd}/carveme_output/L_lactis_fbc_delGLUSx_delGLUSy_detailed.tsv
media_path: ${cfg.wd}/media/media_db_CDM35.tsv
media_name: CDM35
use_parsimonius_fba: False
initial_populations:
  - 0.0039
  - 0.0062