max_uptake_sampler:
  _target_: bk_comms.sampling.MultiDistribution
  dist_1:
    _target_: bk_comms.sampling.SampleSkewNormal
    loc: -2.0
    scale: 0.5
    alpha: 0.0
    clip_above_zero: True
  dist_2:
    _target_: bk_comms.sampling.SampleUniform
    min_val: 1e-3
    max_val: 1e-1
    distribution_type: "log_uniform"
  prob_dist_1: 0.95

k_val_sampler:
  _target_: bk_comms.sampling.SampleUniform
  min_val: 1e-5
  max_val: 100.0
  distribution_type: "log_uniform"

