max_uptake_sampler:
  _target_: bk_comms.sampling.SampleCombinationParticles
  input_experiment_dirs: 
    - ${cfg.wd}/output/mel_indiv_growth/exp_C_perfringens_S107_ga_fit_batch_tests/
    - ${cfg.wd}/output/mel_indiv_growth/exp_E_coli_IAI1_ga_fit_batch_tests/

  epsilon:
    - - 1.17
    - - 0.25

  population_names:
    - C_perfringens_S107
    - E_coli_IAI1

  growth_keys:
    - Growth
    - Growth

  min_growth:
    - -1
    - -1

  max_growth:
    - 100.0
    - 100.0

k_val_sampler:
  _target_: bk_comms.sampling.SampleCombinationParticles
  input_experiment_dirs: 
    - ${cfg.wd}/output/mel_indiv_growth/exp_C_perfringens_S107_ga_fit_batch_tests/
    - ${cfg.wd}/output/mel_indiv_growth/exp_E_coli_IAI1_ga_fit_batch_tests/

  epsilon:
    - - 1.17
    - - 0.25

  population_names:
    - C_perfringens_S107
    - E_coli_IAI1

  growth_keys:
    - Growth
    - Growth

  min_growth:
    - -1
    - -1

  max_growth:
    - 100.0
    - 100.0

toxin_interaction_sampler:
  _target_: bk_comms.sampling.MultiDistribution
  dist_1:
    _target_: bk_comms.sampling.SampleUniform
    min_val: 0
    max_val: 0
    distribution_type: "uniform"
  dist_2:
    _target_: bk_comms.sampling.SampleUniform
    min_val: 10
    max_val: 10000
    distribution_type: "log_uniform"
  prob_dist_1: 0.95

init_population_sampler:
  _target_: bk_comms.sampling.SampleUniform
  min_val: 0.0001
  max_val: 0.0004
  distribution_type: "log_uniform"

