max_uptake_dist:
  _target_: paragem.sampling.MultiDistribution
  dist_1:
    _target_: paragem.sampling.SampleSkewNormal
    loc: -2.0
    scale: 0.25
    alpha: 0.0
    clip_above_zero: True
  dist_2:
    _target_: paragem.sampling.SampleUniform
    min_val: 1e-3
    max_val: 1e-1
    distribution: "log_uniform"
  prob_dist_1: 0.95
k_val_dist:

