max_uptake_sampler:
  _target_: paragem.sampling.SampleCombinationParticles
  input_particles_parameter_vector_regex: 
    - ${user.wd}/output/indiv_growth_test/B_longum_subsp_longum/generation_0/run_0/
    - ${user.wd}/output/indiv_growth_test/C_perfringens_S107/generation_0/run_0/
    - ${user.wd}/output/indiv_growth_test/E_coli_IAI1/generation_0/run_0/
    - ${user.wd}/output/indiv_growth_test/L_paracasei/generation_0/run_0/
    - ${user.wd}/output/indiv_growth_test/L_plantarum/generation_0/run_0/
    - ${user.wd}/output/indiv_growth_test/S_salivarius/generation_0/run_0/
    - ${user.wd}/output/indiv_growth_test/C_ramosum/generation_0/run_0/


  population_names:
    - B_longum_subsp_longum
    - C_perfringens_S107
    - E_coli_IAI1
    - L_paracasei
    - L_plantarum
    - S_salivarius
    - C_ramosum

k_val_sampler:
  _target_: paragem.sampling.SampleCombinationParticles
  input_particles_parameter_vector_regex: 
    - ${user.wd}/output/indiv_growth_test/B_longum_subsp_longum/generation_0/run_0/
    - ${user.wd}/output/indiv_growth_test/C_perfringens_S107/generation_0/run_0/
    - ${user.wd}/output/indiv_growth_test/E_coli_IAI1/generation_0/run_0/
    - ${user.wd}/output/indiv_growth_test/L_paracasei/generation_0/run_0/
    - ${user.wd}/output/indiv_growth_test/L_plantarum/generation_0/run_0/
    - ${user.wd}/output/indiv_growth_test/S_salivarius/generation_0/run_0/
    - ${user.wd}/output/indiv_growth_test/C_ramosum/generation_0/run_0/

  population_names:
    - B_longum_subsp_longum
    - C_perfringens_S107
    - E_coli_IAI1
    - L_paracasei
    - L_plantarum
    - S_salivarius
    - C_ramosum

biomass_rate_constraint_sampler:
  _target_: paragem.sampling.SampleCombinationParticles
  input_particles_parameter_vector_regex: 
    - ${user.wd}/output/indiv_growth_test/B_longum_subsp_longum/generation_0/run_0/
    - ${user.wd}/output/indiv_growth_test/C_perfringens_S107/generation_0/run_0/
    - ${user.wd}/output/indiv_growth_test/E_coli_IAI1/generation_0/run_0/
    - ${user.wd}/output/indiv_growth_test/L_paracasei/generation_0/run_0/
    - ${user.wd}/output/indiv_growth_test/L_plantarum/generation_0/run_0/
    - ${user.wd}/output/indiv_growth_test/S_salivarius/generation_0/run_0/
    - ${user.wd}/output/indiv_growth_test/C_ramosum/generation_0/run_0/

  population_names:
    - B_longum_subsp_longum
    - C_perfringens_S107
    - E_coli_IAI1
    - L_paracasei
    - L_plantarum
    - S_salivarius
    - C_ramosum


toxin_interaction_sampler:
  _target_: paragem.sampling.MultiDistribution
  dist_1:
    _target_: paragem.sampling.SampleUniform
    min_val: 0
    max_val: 0
    distribution_type: "uniform"
  dist_2:
    _target_: paragem.sampling.SampleUniform
    min_val: 10000
    max_val: 10000
    distribution_type: "log_uniform"
  prob_dist_1: 0.80

init_population_sampler:
  _target_: paragem.sampling.SampleUniform
  min_val: 0.00008
  max_val: 0.00008
  distribution_type: "log_uniform"

