max_uptake_sampler:
  _target_: bk_comms.sampling.SampleCombinationParticles
  input_particles_regex: 
    - ${cfg.wd}/output/mel_indiv_growth_10_filtered/B_longum_subsp_longum/generation_0/run_0/*.pkl
    - ${cfg.wd}/output/mel_indiv_growth_10_filtered/C_perfringens_S107/generation_0/run_0/*.pkl
    - ${cfg.wd}/output/mel_indiv_growth_10_filtered/E_coli_IAI1/generation_0/run_0/*.pkl
    - ${cfg.wd}/output/mel_indiv_growth_10_filtered/L_paracasei/generation_0/run_0/*.pkl
    - ${cfg.wd}/output/mel_indiv_growth_10_filtered/L_plantarum/generation_0/run_0/*.pkl
    - ${cfg.wd}/output/mel_indiv_growth_10_filtered/S_salivarius/generation_0/run_0/*.pkl
    - ${cfg.wd}/output/mel_indiv_growth_10_filtered/C_ramosum/generation_0/run_0/*.pkl

  epsilon:
    - - 10000.0
    - - 10000.0
    - - 10000.0
    - - 10000.0
    - - 10000.0
    - - 10000.0
    - - 10000.0

  population_names:
    - B_longum_subsp_longum
    - C_perfringens_S107
    - E_coli_IAI1
    - L_paracasei
    - L_plantarum
    - S_salivarius
    - C_ramosum

  growth_keys:
    - Growth
    - Growth
    - Growth
    - Growth
    - Growth
    - Growth
    - Growth

  min_growth:
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1

  max_growth:
    - 100.0
    - 100.0
    - 100.0
    - 100.0
    - 100.0
    - 100.0
    - 100.0

k_val_sampler:
  _target_: bk_comms.sampling.SampleCombinationParticles
  input_particles_regex: 
    - ${cfg.wd}/output/mel_indiv_growth_10_filtered/B_longum_subsp_longum/generation_0/run_0/*.pkl
    - ${cfg.wd}/output/mel_indiv_growth_10_filtered/C_perfringens_S107/generation_0/run_0/*.pkl
    - ${cfg.wd}/output/mel_indiv_growth_10_filtered/E_coli_IAI1/generation_0/run_0/*.pkl
    - ${cfg.wd}/output/mel_indiv_growth_10_filtered/L_paracasei/generation_0/run_0/*.pkl
    - ${cfg.wd}/output/mel_indiv_growth_10_filtered/L_plantarum/generation_0/run_0/*.pkl
    - ${cfg.wd}/output/mel_indiv_growth_10_filtered/S_salivarius/generation_0/run_0/*.pkl
    - ${cfg.wd}/output/mel_indiv_growth_10_filtered/C_ramosum/generation_0/run_0/*.pkl

  epsilon:
    - - 10000.0
    - - 10000.0
    - - 10000.0
    - - 10000.0
    - - 10000.0
    - - 10000.0
    - - 10000.0

  population_names:
    - B_longum_subsp_longum
    - C_perfringens_S107
    - E_coli_IAI1
    - L_paracasei
    - L_plantarum
    - S_salivarius
    - C_ramosum

  growth_keys:
    - Growth
    - Growth
    - Growth
    - Growth
    - Growth
    - Growth
    - Growth

  min_growth:
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1
    - -1

  max_growth:
    - 100.0
    - 100.0
    - 100.0
    - 100.0
    - 100.0
    - 100.0
    - 100.0

toxin_interaction_sampler:
  _target_: bk_comms.sampling.MultiDistribution
  dist_1:
    _target_: bk_comms.sampling.SampleUniform
    min_val: 0
    max_val: 0
    distribution_type: "uniform"
  dist_2:
    _target_: bk_comms.sampling.SampleUniform
    min_val: 10000
    max_val: 10000
    distribution_type: "log_uniform"
  prob_dist_1: 0.80

init_population_sampler:
  _target_: bk_comms.sampling.SampleUniform
  min_val: 0.00008
  max_val: 0.00008
  distribution_type: "log_uniform"

