_target_: bk_comms.community.Community
_convert_: partial
model_paths: 
  - ${wd}/models/S_cerevisiae/iMM904.xml
model_names:
  - "iMM904"
smetana_analysis_path: "${wd}/carveme_output/lactis_cerevisiae_detailed.tsv"
media_path: "${wd}/media_db_CDM35.tsv"
media_name: "CDM35"
use_parsimonius_fba: False
initial_populations:
  - 0.0062