_target_: bk_comms.distances.DistanceTimeseriesEuclidianDistance
_convert_: partial
exp_data_path: ${cfg.exp_data_path}
exp_sol_keys: ${cfg.exp_sol_keys}
exp_t_key: ${cfg.exp_t_key}
epsilon: ${cfg.epsilon}
final_epsilon: ${cfg.final_epsilon}