_target_: bk_comms.simulator.CometsTimeSeriesSimulation
t_end: 191.9
dt: 0.1
gurobi_home_dir: "${user.gurobi_home_dir}"
comets_home_dir: "${user.comets_home_dir}"
batch_dilution: True
dilution_factor: 0.02
dilution_time: 48
