wd: /Users/bezk/Documents/CAM/research_code/yeast_LAB_coculture/
run_idx: 999
output_dir: ${cfg.wd}/output/mel_mixes_growth_3/mel_multi_mix2_m2_growers/generation_${cfg.algorithm.generation_idx}/run_${cfg.run_idx}/

# Information about the data being used
exp_data_path: ${cfg.wd}/experimental_data/mel_target_data/target_data_pH7_Mix2_Med2.csv
exp_sol_keys:
  - - B_longum_subsp_longum
    - B_longum_subsp_longum
  - - C_perfringens_S107
    - C_perfringens_S107
  - - E_coli_IAI1
    - E_coli_IAI1
  - - L_paracasei
    - L_paracasei
  - - L_plantarum
    - L_plantarum
  - - S_salivarius
    - S_salivarius
  - - C_ramosum
    - C_ramosum

exp_t_key: time
experiment_name: none

epsilon:
  - 100.0
  - 100.0
  - 100.0
  - 100.0
  - 100.0
  - 100.0
  - 100.0

final_epsilon:
  - 0.01
  - 0.01
  - 0.01
  - 0.01
  - 0.01
  - 0.01
  - 0.01

defaults:
  - _self_
  - community: mix2_m2_growers
  - algorithm: NSGAII
  - simulator: time_series_comets_batch_dilution
  - sampler: sampler_mix2_m2_growers
  - distance: abundance_error
  
filter: null
parallel: True
n_processes: 10