# Set the index of a run
run_idx: 999

experiment_dir: ${user.wd}/output/${experiment_name}/${community.model_names.0}/
output_dir: ${experiment_dir}/generation_${algorithm.generation_idx}/run_${run_idx}/

# Names of models being simulated
model_names:
  - null

# Paths to each model in the community
model_paths:
- ${user.data_dir}/models/melanie_data_models/${model_names.0}.xml

# Keys to the objective reaction in each model
objective_reaction_keys:
- Growth

# Name of experiment
experiment_name: test

# Medias to be simulated
sim_media_names:
  - M3
  - M2

# Number of particles to include in visualisations
vis_n_particles: 15


defaults:
  - _self_
  - user: hpc
  - community: default
  - data: M2_M3
  - algorithm: NSGAII
  - simulator: time_series_comets
  - sampler: default_log_uniform
  - distance: fold_change_error_pointwise
  - filter: default_indiv_growth_filter
  - visualisation: indiv
  - override hydra/job_logging: none 
  - override hydra/hydra_logging: none

# Run simulations in parallel
parallel: True

# Number of processes to use for parallel simulations
n_processes: 10

hydra.run.dir: . 
hydra.output_subdir: null
hydra.job.chdir: True
