"""
Requires a model to be set

"""

run_idx: 999
output_dir: ${user.wd}/output/${experiment_name}/${community.model_names.0}/generation_${algorithm.generation_idx}/run_${run_idx}/


model_names:
  - null

model_paths:
- ${user.wd}/models/melanie_data_models/${model_names.0}.xml

objective_reaction_keys:
- Growth

experiment_name: test

sim_media_names:
  - M3
  - M2

defaults:
  - _self_
  - user: local
  - community: ${model_names.0}
  - data: M3
  - algorithm: NSGAII
  - simulator: time_series_comets
  - sampler: default_log_uniform
  - distance: fold_change_error_pointwise
  - filter: default_indiv_growth_filter
  - override hydra/job_logging: none 
  - override hydra/hydra_logging: none

parallel: True
n_processes: 2

hydra.run.dir: . 
hydra.output_subdir: null
hydra.job.chdir: True
