_target_: bk_comms.parameter_estimation.GeneticAlgorithm
n_particles_batch: 8
population_size: 25
mutation_probability: 0.0
hotstart_particles_regex:
generation_idx: 0
epsilon_alpha: 0.2
simulator: ${cfg.simulator}
experiment_name: ${cfg.experiment_name}
base_community: ${cfg.community}
distance_object: ${cfg.distance}
output_dir: ${cfg.output_dir}
particle_filter: ${cfg.filter}