_target_: bk_comms.parameter_estimation.GeneticAlgorithm
n_particles_batch: 8
population_size: 10
mutation_probability: 0.1
epsilon_alpha: 0.2
simulator: ${cfg.simulator}
experiment_name: ${cfg.experiment_name}
base_community: ${cfg.community}
distance_object: ${cfg.distance}
max_uptake_sampler: ${cfg.sampler.max_uptake_sampler}
k_val_sampler: ${cfg.sampler.k_val_sampler}
init_population_sampler: ${cfg.sampler.init_population_sampler}
output_dir: ${cfg.output_dir}
filter: ${cfg.filter}

