_target_: bk_comms.parameter_estimation.NSGAII
population_size: 50
n_particles_batch: 10
mutation_probability: 0.05
hotstart_particles_regex:
generation_idx: 0
max_generations: 1
crossover_type: parameterwise
mutate_type: parameterwise
simulator: ${cfg.simulator}
experiment_name: ${cfg.experiment_name}
base_community: ${cfg.community}
distance_object: ${cfg.distance}
output_dir: ${cfg.output_dir}
particle_filter: ${cfg.filter}