wd: /Users/bezk/Documents/CAM/research_code/yeast_LAB_coculture/
run_idx: 999
output_dir: ${cfg.wd}/output/exp_iMM904_ga_fit_batch_tests/run_${cfg.run_idx}/

# Information about the data being used
exp_data_path: ${cfg.wd}/experimental_data/Figure1B_fake_data.csv
exp_sol_keys:
  - - yeast_fc
    - iMM904
exp_t_key: time
experiment_name: none

epsilon:
  - 100.0
final_epsilon:
  - 100.0

defaults:
  - _self_
  - community: iMM904
  - algorithm: genetic_algorithm
  - simulator: time_series_comets_batch_dilution
  - sampler: default_log_uniform_population
  - distance: fold_change_error
  - filter: iMM904_viable_growth

parallel: True
n_processes: 8