wd: /Users/bezk/Documents/CAM/research_code/yeast_LAB_coculture/
run_idx: 999
output_dir: ${cfg.wd}/output/mel_mixes_growth/mel_multi_mix2_m2_growers_test/run_${cfg.run_idx}/

# Information about the data being used
exp_data_path: ${cfg.wd}/experimental_data/mel_target_data/target_data_pH7_Mix2_Med2.csv
exp_sol_keys:
  - - C_perfringens_S107
    - C_perfringens_S107
  - - E_coli_IAI1
    - E_coli_IAI1

exp_t_key: time
experiment_name: none

epsilon:
  - 100.0
  - 100.0

final_epsilon:
  - 100.0
  - 100.0

defaults:
  - _self_
  - community: mix2_m2_growers_ecol_perf
  - algorithm: NSGAII
  - simulator: time_series_comets_batch_dilution
  - sampler: sampler_mix2_m2_growers_E_P
  - distance: abundance_error
  
filter:
parallel: True
n_processes: 8