_target_: bk_comms.lo_filters.ViableGrowthCombineParticles
input_experiment_dirs: 
  - ${user.wd}/output/mel_indiv_growth/exp_B_longum_subsp_longum_ga_fit_batch_tests/
  - ${user.wd}/output/mel_indiv_growth/exp_C_perfringens_S107_ga_fit_batch_tests/
  - ${user.wd}/output/mel_indiv_growth/exp_E_coli_IAI1_ga_fit_batch_tests/
  - ${user.wd}/output/mel_indiv_growth/exp_L_paracasei_ga_fit_batch_tests/
  - ${user.wd}/output/mel_indiv_growth/exp_L_plantarum_ga_fit_batch_tests/
  - ${user.wd}/output/mel_indiv_growth/exp_S_salivarius_ga_fit_batch_tests/

epsilon:
  - - 0.25
  - - 1.17
  - - 0.25
  - - 0.51
  - - 1.22
  - - 0.25

population_names:
  - B_longum_subsp_longum
  - C_perfringens_S107
  - E_coli_IAI1
  - L_paracasei
  - L_plantarum
  - S_salivarius

growth_keys:
  - Growth
  - Growth
  - Growth
  - Growth
  - Growth
  - Growth

min_growth:
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1

max_growth:
  - 100.0
  - 100.0
  - 100.0
  - 100.0
  - 100.0
  - 100.0
