_target_: paragem.lo_filters.ViableGrowthFilter
population_names:
  - L_lactis_fbc_delGLUSx_delGLUSy
  - iMM904
growth_keys:
  - Growth
  - BIOMASS_SC5_notrace
min_growth:
  - 0.0
  - 0.001
max_growth:
  - 0.0
  - 1.0
