_target_: bk_comms.simulator.CometsTimeSeriesSimulation
t_end: 191.9
dt: 0.1
gurobi_home_dir: "/Library/gurobi950/macos_universal2"
comets_home_dir: "/Users/bezk/Documents/CAM/research_code/comets"

batch_dilution: True
dilution_factor: 0.02
dilution_time: 48