_convert_: partial
_target_: bk_comms.community.Community
initial_populations:
- 0.05
media_name: M1
media_path: null
model_names:
- P_copri
model_paths:
- P_copri.xml
smetana_analysis_path: null
use_parsimonius_fba: false
