_convert_: partial
_target_: bk_comms.community.Community
initial_populations:
- 0.05
media_name: M1
media_path: null
model_names:
- S_typhimurium_ATCC14028
model_paths:
- S_typhimurium_LT2.xml
smetana_analysis_path: null
use_parsimonius_fba: false
